package edu.upv.poo;

import java.awt.Color;
import java.util.ArrayList;

public class ToolsFrame extends javax.swing.JFrame {

    private final ArrayList<ToolsListener> toolsListener=
            new ArrayList<>();
    
    private int size = 5;
    
    private void notifyToolChanged(String toolName) {
        for (ToolsListener tl : toolsListener)
            tl.toolChanged(new ToolChangedEvent(this, toolName));
    }
    
    private void notifyColorChanged(Color color, String colorName){
        for (ToolsListener tl : toolsListener) {
            ColorChangedEvent e = new ColorChangedEvent(
                    this, color, colorName);
            tl.colorChanged(e);
        }
    }
    
    private void notifySizeChanged(int size) {
        for (ToolsListener tl : toolsListener)
            tl.sizeChanged(new SizeChangedEvent(this, size));
    }
    
    /**
     * Creates new form ToolsFrame
     */
    public ToolsFrame() {
        initComponents();
    }

    public void addToolsListener(ToolsListener tl) {
        if (tl == null || toolsListener.indexOf(tl) >= 0)
            return;
        toolsListener.add(tl);
    }
    
    public void removeToolsListener(ToolsListener tl) {
        if (tl == null) return;
        toolsListener.remove(tl);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnToolPencil = new javax.swing.JButton();
        btnColorBlack = new javax.swing.JButton();
        btnColorBlue = new javax.swing.JButton();
        btnColorGreen = new javax.swing.JButton();
        btnToolLine = new javax.swing.JButton();
        lblSize = new javax.swing.JLabel();
        btnSizeDecrease = new javax.swing.JButton();
        btnSizeIncrease = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnToolPencil.setText("Pencil");
        btnToolPencil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolPencilActionPerformed(evt);
            }
        });

        btnColorBlack.setText("Black");
        btnColorBlack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorBlackActionPerformed(evt);
            }
        });

        btnColorBlue.setText("Blue");
        btnColorBlue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorBlueActionPerformed(evt);
            }
        });

        btnColorGreen.setText("Green");
        btnColorGreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorGreenActionPerformed(evt);
            }
        });

        btnToolLine.setText("Line");
        btnToolLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToolLineActionPerformed(evt);
            }
        });

        lblSize.setText("5");

        btnSizeDecrease.setText("-");
        btnSizeDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeDecreaseActionPerformed(evt);
            }
        });

        btnSizeIncrease.setText("+");
        btnSizeIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeIncreaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnToolPencil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorBlack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnColorGreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnToolLine, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSizeDecrease)
                        .addGap(24, 24, 24)
                        .addComponent(lblSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSizeIncrease)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSizeDecrease)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSizeIncrease)
                        .addComponent(lblSize)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolPencil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnToolLine)
                .addGap(102, 102, 102)
                .addComponent(btnColorBlack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorBlue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnColorGreen)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnToolPencilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolPencilActionPerformed
        notifyToolChanged("Pencil");
    }//GEN-LAST:event_btnToolPencilActionPerformed

    private void btnColorBlackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorBlackActionPerformed
        notifyColorChanged(Color.BLACK, "Black");
    }//GEN-LAST:event_btnColorBlackActionPerformed

    private void btnColorBlueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorBlueActionPerformed
        notifyColorChanged(Color.BLUE, "Blue");
    }//GEN-LAST:event_btnColorBlueActionPerformed

    private void btnColorGreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorGreenActionPerformed
        notifyColorChanged(Color.GREEN, "Green");
    }//GEN-LAST:event_btnColorGreenActionPerformed

    private void btnToolLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToolLineActionPerformed
        notifyToolChanged("Line");
    }//GEN-LAST:event_btnToolLineActionPerformed

    private void btnSizeDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeDecreaseActionPerformed
        if (size <= 5) return;
        size--;
        lblSize.setText(Integer.toString(size));
        notifySizeChanged(size);
    }//GEN-LAST:event_btnSizeDecreaseActionPerformed

    private void btnSizeIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeIncreaseActionPerformed
        size++;
        lblSize.setText(Integer.toString(size));
        notifySizeChanged(size);
    }//GEN-LAST:event_btnSizeIncreaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnColorBlack;
    private javax.swing.JButton btnColorBlue;
    private javax.swing.JButton btnColorGreen;
    private javax.swing.JButton btnSizeDecrease;
    private javax.swing.JButton btnSizeIncrease;
    private javax.swing.JButton btnToolLine;
    private javax.swing.JButton btnToolPencil;
    private javax.swing.JLabel lblSize;
    // End of variables declaration//GEN-END:variables
}
